baseURL = "https://ayyrixx.github.io"
languageCode = "en-us"
title = "ayyrixx"
theme = "hugo-PaperMod"

[params]
  author = "Aliyan"

[author]
  name = "Aliyan"
  email = "p250079@pwr.nu.edu.pk"

[params.profileMode]
    enabled = true
    title = "Aliyan"
    subtitle = "Greeting Worlds"
    imageUrl = "ayyrixx.jpg"
    imageTitle = "Aliyan Abdullah"
    imageWidth = 200
    imageHeight = 200



# ---------------------------
# Navigation Menu
# ---------------------------
[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/ayyrixx"
    weight = 4

