baseURL = "https://example.org/"
languageCode = "en-us"
title = "Aliyan's Blog"
theme = "hugo-PaperMod"

[author]
  name = "Aliyan"
  email = "p250079@pwr.nu.edu.pk"

# ---------------------------
# Navigation Menu
# ---------------------------
[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/ayyrixx"
    weight = 4

# ---------------------------
# Params for PaperMod Theme
# ---------------------------
[params]
  showReadingTime = true
  showShareButtons = true
  enableEmoji = true
  mainSections = ["posts"]  # Important: Hugo will list all posts in this folder